### ISSUE TITLE
Фикс отсутствия патрон у Психа ДЗ

### ISSUE THREAD

**Issue by HappyWolfovich** [Spac3e/nextoren-breach#1]
[shared.zip](https://github.com/Spac3e/nextoren-breach/files/13516284/shared.zip)
крч держи говняшку, там из-за неправильно AmmoType патроны ГОВНО, нет патрон при спавне.

addons\[weapons]_no_260_kk_ins2\lua\weapons\cw_kk_ins2_dragunov вот тут если че.
ХЗ правильно ли я сделал ишью.

**Comment by Spac3e** [comment]
Проблема cw 2.0, будет исправленное в патче.
