### ISSUE TITLE
Обьясните дауну как скачать и запустить эту сборку

### ISSUE THREAD

**Issue by Iskirle** [Spac3e/nextoren-breach#2]
Да я такой тупой и не понял. Помогите пожалуйста подробно расписав тут как нужно ее установить для запуска

**Comment by maleyvich** [comment]
богу помолиться

**Comment by X0lik** [comment]
Накатить чистый сервер через steamcmd.exe и перекинуть в GarrysModDS/garrysmod/ все эти папки

Плюс в батнике прописать загрузку определенной мапы и режима

**Comment by Iskirle** [comment]
Можешь пожалуйста написать команды. Я в этом вообще не разбираюсь ((запускаю чисто для себя))

**Comment by Iskirle** [comment]
Обьясни пожалуйста что такое батник и что такое GarrysModDS/garrysmod/

**Comment by X0lik** [comment]
Батник: [https://www.youtube.com/watch?v=vXrPulunl88](url)
/GarrysModDS/garrysmod/ - это путь, где steamcmd.exe создать тебе сервер
